apiVersion: psmdb.percona.com/v1-11-0
kind: PerconaServerMongoDB
metadata:
  name: mongo-cluster
spec:
  platform: openshift
  crVersion: 1.11.0
  image: percona/percona-server-mongodb:4.4.10-11
  allowUnsafeConfigurations: true
  upgradeOptions:
    apply: 4.4-recommended
    schedule: "0 2 * * *"
  secrets:
    users: mongo-cluster-secrets
  replsets:
    - name: rs0
      size: 1
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 1Gi
      podSecurityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

  sharding:
    enabled: false
